### ISSUE TITLE
Possible to expose the IsFiltering observable?

### ISSUE THREAD

**Issue by Elindalyne** [thinkloop/knockout-js-progressive-filter#2]
Looking at the script right now it doesn't look like IsFiltering is exposed.

IsFiltered appears to be getting set immediately and I really need something I can observe to let the client know when something is finished filtering.

Let me know if I'm missing something!
Thanks

**Comment by thinkloop** [comment]
Hello,

All the "props" are exposed through the progressivefilter object:

   props.unfilteredCollection
   props.unfilteredCollectionIndex
   pops.isFiltering
   props.filterFunction
   props.batchSize
   props.add

So to access isFiltering, you can simply do something like filteredItems.progressivefilter.isFiltering().

I updated the fiddle with an example of this: http://jsfiddle.net/thinkloop/Mkg72/

See the new p element with data-bind="text: 'isFiltering? ' + filteredItems.progressivefilter.isFiltering()"

Good?
