### ISSUE TITLE
Updating ViewModel of New Item Pushed into List

### ISSUE THREAD

**Issue by johnmcmillion** [thinkloop/knockout-js-progressive-filter#3]
This is an excellent extension to knockout, really helpful onload.  However I'm not sure which list to push into, filtered or unfiltered after load, to keep them in sync.  I can push new items to both, but then that means I have to update viewmodels in both lists too, for changes.  For some reason though, items that were in the original list when filterProgressive(originalList) is first called, do get updates in both lists, with updates to an original list item.  It seems this observability is lost for new pushes though, unless I re-run filterProgressive for the change, but that's kind of slow/too much just for a single item addition/deletion.  Any ideas?

**Comment by thinkloop** [comment]
Hello!

Generally you should only manage the "items" model, and let the component auto-update the filteredItems collection. There is an addFunction() that you can override with your own logic, to, say, pre-filter an item before adding it tot he filtered items without running the filter. But unless you see specific performance issue that needs to be resolved, I wouldn't bother as the purpose of this component is to be able to filter large-collections in a non-blocking way, letting the rest of the UI do it's thing without hiccup.

**Comment by johnmcmillion** [comment]
Thank you for your suggestion.  I would like to manage the "items" model too, but if I push a new item into the "items" model after load, with say self.items.push(newItem), the filteredItems collection remains unchanged.  Same if I remove an item from the "items" model. Haven't had any luck with the addFunction yet, but I may need to just spend some more time with it.  I tried going the other direction with filteredItems.progressiveFilter.add(newItem), but then the "items" model remains unchanged.  Thank you for any insights!

**Comment by thinkloop** [comment]
Hey John,

I didn't use the right wording there. You are right that you should not have to manually update the filteredItems collection. However, to allow for flexibility of implementation, there is no forced or built-in updating of the filteredItems collection. Instead, you should subscribe to changes in the items collection, and then handle the update from your code, either by invoking filter(), filterProgressive() or some custom logic that adds that one item if it meets your filter function criteria.
